### ISSUE TITLE
ChatTopBar does not work on Firefox.

### ISSUE THREAD

**Issue by JC3** [JC3/SEUserScripts#1]
ChatTopBar does not work on Firefox.

Working on this on firefox-greasemonkey branch. Hit a wall for now.

**Comment by Shog9** [comment]
I've submitted a patch that fixes this: https://github.com/JC3/SEUserScripts/pull/11

**Comment by JC3** [comment]
New PR https://github.com/JC3/SEUserScripts/pull/14

**Comment by JC3** [comment]
Tested and merged in 1.12 (https://github.com/JC3/SEUserScripts/commit/5d8f65ab9d4d58d2addb474820af9c512ddf51e1).
